develop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mymap/', include('mymap.urls')),
    path('form/', include('face_r.urls')),
    path('localmap/', include('localmap.urls')),
    path('routesearch/', include('routesearch.urls')),
    path('', include('healthcheck.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

face_r/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.form, name='form'),
    path('scan/', views.scan, name='scan'),
    path('testface_r/', views.testface_r, name='testface_r'),
]

mymap/urls.py
from django.urls import path
from . import views

#namespaceの設定
app_name = 'mymap'

urlpatterns = [
path('', views.index, name='index'),
path('signup/', views.SignUp.as_view(), name='signup'), 
path('login/', views.Login.as_view(), name='login'),
path('overview/', views.Overview, name='overview'),
path('logout/', views.Logout.as_view(), name='logout'),
path('mypage/', views.Mypage, name='mypage'),
]

face_r/views.py
from django.shortcuts import render
from django.http import HttpResponse

import asyncio
import glob
import io
import json
import MySQLdb
import os
import requests
import sys
import time
import uuid
from urllib.parse import urlparse
from io import BytesIO
from PIL import Image, ImageDraw
from azure.cognitiveservices.vision.face import FaceClient
from msrest.authentication import CognitiveServicesCredentials
from azure.cognitiveservices.vision.face.models import TrainingStatusType, Person, SnapshotObjectType, OperationStatusType

# Create your views here.

def scan(request):

    subscription_key = '146e40172163433cb62be9bedc90c95e'
    assert subscription_key

    face_api_url = 'https://18ticket-face.cognitiveservices.azure.com/face/v1.0/detect'

    image_url = 'https://upload.wikimedia.org/wikipedia/commons/5/56/Donald_Trump_official_portrait.jpg'
    
    if request.POST.get('url'):
        image_url = request.POST.get('url')

    headers = {
        #'Content-Type': 'application/octet-stream',
        'Ocp-Apim-Subscription-Key': subscription_key}

    params = {
        'returnFaceId': 'true',
        'returnFaceLandmarks': 'false',
        'returnFaceAttributes': 'age,gender,headPose,smile,facialHair,glasses,emotion,hair,makeup,occlusion,accessories,blur,exposure,noise',
    }

    #with open(r"imagePATH\image.jpg", 'rb') as f:
       #img = f.read()

    response = requests.post(
        face_api_url,
        params = params,
        headers = headers,
        json = {"url": image_url}
        #data=img
    )

    faceparam_buf = response.json()
    faceparam = faceparam_buf[0]

    id = (faceparam['faceRectangle']['top'] * faceparam['faceRectangle']['left'] * faceparam['faceRectangle']['width'] * faceparam['faceRectangle']['height']) % 1788 + 1
    id = (int(id))

    cnt = MySQLdb.connect(
        host = 'mysql-server-60149727.mysql.database.azure.com',
        port = 3306,
        db = 'citycode',
        user = 'fy20user@mysql-server-60149727',
        password = 'fy20P@ssw0rd',
        charset = 'utf8'
    )

    db = cnt.cursor()
    sql = "SELECT todoufuken FROM citycode WHERE id=" + str(id) + ';';
    db.execute(sql)
    todoufuken_tup = db.fetchall()[0]
    todoufuken = todoufuken_tup[0]

    sql = "SELECT sikuchoson FROM citycode WHERE id=" + str(id) + ';';
    db.execute(sql)
    sikuchoson_tup = db.fetchall()[0]
    sikuchoson = sikuchoson_tup[0]

    place = todoufuken + sikuchoson

    sql = "SELECT code FROM citycode WHERE id=" + str(id) + ';';
    db.execute(sql)
    code_tup = db.fetchall()[0]
    code = code_tup[0]
    pcode = code[:-1]

    db.close()
    cnt.close()
    return render(request, 'face_r/scan.html', {'pcode': pcode, 'place': place, 'url': image_url})


def form(request):
    return render(request, 'face_r/photoform.html')


def testface_r(request):
    return render(request, 'face_r/index.html')

face_r/templates/face_r/index.html
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>HPE Training</title>
</head>
<body>
    <h1>Hello Training</h1>
</body>
</html>

face_r/templates/face_r/photoform.html
<!DOCTYPE html>
<html lang="ja">
{% load static %}
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/textform.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/traveltop.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
    <script src="http://code.jquery.com/jquery-3.3.1.min.js" defer></script>　
    <script  type="text/javascript" src="{% static 'js/hamberger_menu.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <title>Specify an Image</title>
  </head>
 
  <body>

    <div class="hamberger_menu">
        
      <div class="hamberger_line">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
      <nav class="hamberger_list">
        <ul>
          <li><a href="{% url 'mymap:index' %}">Home</a></li>
          <li><a href="{% url 'mymap:overview' %}">Overview</a></li>            
          {% if user.is_authenticated %}
          <li><a class="nav-item nav-link" href="{% url 'mymap:mypage' %}">Mypage</a></li>
          <li><a class="nav-item nav-link" href="../../form">Travel planning</a></li>
          <li><a class="nav-item nav-link" href="{% url 'mymap:logout' %}">Logout</a></li>
          {% else %}
          <li class="nav-item">
          <a class="nav-item nav-link" href="{% url 'mymap:login' %}">Login</a></li>
          <li><a class="nav-item nav-link"  href="{% url 'mymap:signup' %}">Creat Account</a></li>
          {% endif %}
        </ul>
      </nav>
      <div class="container">
        <div class="loginPage_contents">
          <h1 class="h3 loginPage_contents_title"><h1>Specify an Image</h1></h1>
          <br><hr><br>
        </div>
      </div>  
 
      <div class="cp_iptxt">
        <form name="photo" method="POST" action="./scan/" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="submit" value="OK?">
          <input class="ef" type="text" name="url" size="20" placeholder="http://...">
          <label>画像</label>
          <span class="focus_line"></span>
        </form>
      </div>
  
    <footer>
      <address>Copyright(C)2020 team青春18きっぷ,Allright Reserved.</address>
    </footer>
  </body>
</html>

face_r/templates/face_r/scan.html
<!DOCTYPE  html>
<html lang="ja">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/textform.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/traveltop.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
    <script src="http://code.jquery.com/jquery-3.3.1.min.js" defer></script>　
    <script  type="text/javascript" src="{% static 'js/hamberger_menu.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <title>Specify an Image</title>
  </head>
  
  <body>

    <div class="hamberger_menu">
        
      <div class="hamberger_line">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
      <nav class="hamberger_list">
        <ul>
          <li><a href="{% url 'mymap:index' %}">Home</a></li>
          <li><a href="{% url 'mymap:overview' %}">Overview</a></li>            
          {% if user.is_authenticated %}
          <li><a class="nav-item nav-link" href="{% url 'mymap:mypage' %}">Mypage</a></li>
          <li><a class="nav-item nav-link" href="../../form">Travel planning</a></li>
          <li><a class="nav-item nav-link" href="{% url 'mymap:logout' %}">Logout</a></li>
          {% else %}
          <li class="nav-item">
          <a class="nav-item nav-link" href="{% url 'mymap:login' %}">Login</a></li>
          <li><a class="nav-item nav-link"  href="{% url 'mymap:signup' %}">Creat Account</a></li>
          {% endif %}
        </ul>
      </nav>
      <div class="container">
        <div class="loginPage_contents">
          <h1 class="h3 loginPage_contents_title"><h1>おススメの場所は{{place}}です</h1></h1>
        </div>
      </div>

    <p>
      <img src="{{url}}" alt="画像" title="{{url}}">
    </p>

    <form name="form" method="POST" action="../../localmap/" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="hidden" name="num" value="{{pcode}}">
      <input type="hidden" name="spot" value="{{place}}">
      <p><input type="submit" id="button" name="button" value="OK?"></p>
    </form>
 
    <footer>
      <address>Copyright(C)2020 team青春18きっぷ,Allright Reserved.</address>
    </footer>
  </body>
</html>